name: HelloWorld
on: workflow_dispatch
jobs:
 hello-job:
  runs-on: ubuntu-latest
  steps:
   - name: Print Hello World
     run: |
      echo "Hello World"
      echo "New Line"
      echo "${{ vars.MY_NAME }}"
      echo "${{ secrets.MY_PASS }}"
